### ISSUE TITLE
[Feature Request] Force state update

### ISSUE THREAD

**Issue by HarvsG** [mdeweerd/zha-toolkit#113]
A common issue with ZHA is that the state does not update correctly for a few devices in HA after a batch or light group turn_off/turn_on command. 

It would be great to have a service call to request state updates from device(s)/groups that we could call after a batch command.

**Comment by HarvsG** [comment]
Ok sounds as if the feature is already implemented. Just for clarity, which service would I call if I just wanted to know the on/off status of a bulb?

**Comment by mdeweerd** [comment]
zha_toolkit.attr_read - On/Off cluster, cluster 6, attribute 0.

Example:
```yaml
service: zha_toolkit.attr_read
data:
  ieee: light.tz3000_dbou1ap4_ts0505a_9afc91fe_level_light_color_on_off
  cluster: 6
  attribute: 0
```

**Comment by HarvsG** [comment]
Solved:
I use this in an automation to force light state updates:
```yaml
alias: "[Lighting] Update states"
description: >-
  Sometime, particularly when batch turn on/turn off operations are performed.
  Lights' states in home assistant don't get updated accurately. This automation
  forces a state update.
trigger: []
condition: []
action:
  - repeat:
      for_each: >-
        {{states.light | map(attribute='entity_id') | select('in',
        integration_entities('zha')) | list }}
      sequence:
        - continue_on_error: true
          service: zha_toolkit.attr_read
          data:
            ieee: "{{ repeat.item }}"
            cluster: 6
            attribute: 0
mode: single
```

**Comment by mdeweerd** [comment]
Great, added as an example: https://github.com/mdeweerd/zha-toolkit/blob/main/examples/script_request_all_light_states.yaml .

**Comment by HarvsG** [comment]
Hmm 
When I call the service from the Dev tools UI, HA actually updates the state. But when I call it from an automation, no state change actually happens.... (though the call_service completes)

```yaml
alias: "[Lighting] update state after change"
description: ""
trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: light
      service: turn_off
    id: turn_off
  - platform: event
    event_type: call_service
    event_data:
      domain: light
      service: turn_on
    id: turn_on
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - choose:
      - conditions:
          - condition: trigger
            id: turn_on
        sequence:
          - repeat:
              for_each: "{{ trigger.event.data.service_data.entity_id}}"
              sequence:
                - if:
                    - condition: template
                      value_template: "{{is_state(repeat.item,'off')}}"
                  then:
                    - service: zha_toolkit.attr_read
                      data:
                        ieee: "{{ repeat.item }}"
                        cluster: 6
                        attribute: 0
                        event_done: zha_correction_event
                        fail_exception: false
                        tries: 3
                    - delay:
                        hours: 0
                        minutes: 0
                        seconds: 1
                        milliseconds: 0
                    - if:
                        - condition: template
                          value_template: "{{is_state(repeat.item,'on')}}"
                      then:
                        - service: persistent_notification.create
                          data:
                            message: "{{repeat.item}} was corrected"
                      else:
                        - service: persistent_notification.create
                          data:
                            message: "{{repeat.item}} was NOT corrected"
      - conditions:
          - condition: trigger
            id: turn_off
        sequence:
          - repeat:
              for_each: "{{ trigger.event.data.service_data.entity_id}}"
              sequence:
                - if:
                    - condition: template
                      value_template: "{{is_state(repeat.item,'on')}}"
                  then:
                    - service: zha_toolkit.attr_read
                      data:
                        ieee: "{{ repeat.item }}"
                        cluster: 6
                        attribute: 0
                        event_done: zha_correction_event
                        fail_exception: false
                        tries: 3
                    - delay:
                        hours: 0
                        minutes: 0
                        seconds: 1
                        milliseconds: 0
                    - if:
                        - condition: template
                          value_template: "{{is_state(repeat.item,'off')}}"
                      then:
                        - service: persistent_notification.create
                          data:
                            message: "{{repeat.item}} was corrected"
                      else:
                        - service: persistent_notification.create
                          data:
                            message: "{{repeat.item}} was NOT corrected"
mode: parallel

```

**Comment by HarvsG** [comment]
Increasing the delay to 7 seconds seems to work nicely.
```
alias: "[Lighting] update state after change"
description: ""
trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: light
      service: turn_off
    id: turn_off
  - platform: event
    event_type: call_service
    event_data:
      domain: light
      service: turn_on
    id: turn_on
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 7
      milliseconds: 0
  - choose:
      - conditions:
          - condition: trigger
            id: turn_on
        sequence:
          - repeat:
              for_each: "{{ trigger.event.data.service_data.entity_id}}"
              sequence:
                - if:
                    - condition: template
                      value_template: "{{is_state(repeat.item,'off')}}"
                  then:
                    - service: zha_toolkit.attr_read
                      data:
                        ieee: "{{ repeat.item }}"
                        cluster: 6
                        attribute: 0
                        event_done: zha_correction_event
                        fail_exception: false
                        tries: 3
      - conditions:
          - condition: trigger
            id: turn_off
        sequence:
          - repeat:
              for_each: "{{ trigger.event.data.service_data.entity_id}}"
              sequence:
                - if:
                    - condition: template
                      value_template: "{{is_state(repeat.item,'on')}}"
                  then:
                    - service: zha_toolkit.attr_read
                      data:
                        ieee: "{{ repeat.item }}"
                        cluster: 6
                        attribute: 0
                        event_done: zha_correction_event
                        fail_exception: false
                        tries: 3
mode: parallel
```
