### ISSUE TITLE
Automation getting: 'Discarding _save_attribute event' using zha_toolkit.execute

### ISSUE THREAD

**Issue by antfurn** [mdeweerd/zha-toolkit#123]
Hi, anyone seen this error? **Discarding _save_attribute event**
I have two radiator values that my automation is reading the value open position of every 5mins. This is has been working great for many months but now I'm seeing this error in the logs. As far as I know... nothing has changed so I'm wondering why it's now failing to read the values. If I go to the device and directly read the value, the correct current value is being read and returned.

![image](https://user-images.githubusercontent.com/4171512/212115541-9df78996-faa0-4e42-ac7b-e67187f5031c.png)

```
This error originated from a custom integration.

Logger: zigpy.appdb
Source: custom_components/zha_toolkit/utils.py:778
Integration: 🧰 ZHA Toolkit Service (documentation, issues)
First occurred: 10 January 2023 at 19:40:00 (1060 occurrences)
Last logged: 15:45:00

Discarding _save_attribute event
```

Automation is:
```
alias: Read additional thermostat values and store them to sensors
description: Read additional thermostat values and store them to sensors
trigger:
  - platform: time_pattern
    minutes: /5
condition: []
action:
  - service: zha_toolkit.execute
    data:
      command: attr_read
      ieee: 80:4b:50:ff:fe:4a:09:18
      endpoint: 1
      cluster: 513
      attribute: 16388
      state_id: sensor.lounge_radiator_thermostat_valve_raw
      allow_create: true
  - service: zha_toolkit.execute
    data:
      command: attr_read
      ieee: 84:fd:27:ff:fe:8a:ee:9c
      endpoint: 1
      cluster: 513
      attribute: 16388
      state_id: sensor.dining_radiator_thermostat_valve_raw
      allow_create: true
```

Manual read: 
![image](https://user-images.githubusercontent.com/4171512/212117272-6ff8cdab-58ff-4804-abfb-37fd5b8ca96e.png)
