### ISSUE TITLE
actual setting set_min/max_temperature not implemented

### ISSUE THREAD

**Issue by michib-xx** [mdeweerd/zha-toolkit#129]
https://github.com/mdeweerd/zha-toolkit/blob/e2531c1386c285e36ab235186e8415cb6fa94d0c/examples/script_danfoss_ally_configure.yaml#L83

The script does define the fields `set_min|max_temperature`, but there is no service call (to `zha_toolkit.attr_write`?) implemented, that would actually set the values.

**Comment by mdeweerd** [comment]
You are right, probably accidentally deleted when adding other configurations - I was wondering why I could go higher on some of my valves.

Corrected in the main branch: https://github.com/mdeweerd/zha-toolkit/blob/main/examples/script_danfoss_ally_configure.yaml .

I also corrected the attribute id when the open window report configuration is read back - not very important in itself, but I watch the 'zha_done' event sometimes while configuring.

FYI, I also define another script which calls the danfoss configuration script so that I easily update and reconfigure my valves.  Example with just two valves:

```yaml
alias: Setup/Configure DANFOSS VALVES
sequence:
  - alias: Configure Kitchen
    service: script.conf_danfoss_ally
    data:
      device: 05a5be28148c6e810c20f4386565cb25
      set_max_temperature: 22
      set_min_temperature: 8
      enable_open_window: true
      view_direction: true
      orientation: false
      covered: true
  - service: script.conf_danfoss_ally
    data:
      device: 7d16a871a8caa808d80e23f5d92ca65d
      orientation: false
      view_direction: true
      covered: true
      enable_open_window: false
    alias: Configure Room X
```
