### ISSUE TITLE
Problem with write attribute to TS011F

### ISSUE THREAD

**Issue by barcik75** [mdeweerd/zha-toolkit#136]
Hi,
Thank you for your work. I found this addon when I searched how to delete energy delivered from my Smart Socket.
I try reset this value to 0. First. I read this attribute. I wrote:
```
service: zha_toolkit.attr_read
data:
  cluster: 1794
  attribute: 0
  csvout: test.csv
  ieee: sensor.microwave_oven_energy
```
And I got:
`2023-02-02T20:01:51.332227+00:00,TuyaZBMeteringCluster,current_summ_delivered,154,0x0000,0x0702,1,a4:c1:38:48:57:68:9f:fd,,0x25`
And it is ok. Mayby one problem, when I used cluster: 0x0702 nothing happned.
Next I tried cange this value:
```
service: zha_toolkit.attr_write
data:
  ieee: sensor.microwave_oven_energy
  cluster: 1794
  attribute: 0
  read_before_write: true
  read_after_write: true
  csvout: test.csv
  attr_val: "0"
```
But nothing happened. A green tick appeared on the button but, no new lines in test.csv file. I tried change "0" to '0' or 0. Not helped. When is empty I can't execute service, so, IMHO, the command syntax is correct
Am I doing something wrong or is it just not possible to change this value?
I'm new to Zigbee and controlling it, so I chose ZHA integration because it seems the simplest. From the ZHA level I can also manage this cluster and read the value 154, but to change it I need the manufacturer's code, which I don't know what it is and I don't know where to find it. It seemed to me that using your add-on I would be able to do without this code.
![obraz](https://user-images.githubusercontent.com/40303640/216445408-306cdab9-da13-49e1-9d9e-06ae1ea5c815.png)
