### ISSUE TITLE
add exmaple on how to set last seen attribute

### ISSUE THREAD

**Issue by regevbr** [mdeweerd/zha-toolkit#223]
I created the following HA automation to set the last seen attribute on all ZHA devices, similar to how zigbee2mqtt does. Think it will be informative to people as I couldn't find any other solution published anywhere.

@mdeweerd can you please add it to the docs where relevant?

```yaml
alias: zha last seen attribute
description: set the last seen attribute on all entities of zha end devices
trigger:
  - platform: time_pattern
    seconds: "5"
condition: []
action:
  - service: zha_toolkit.zha_devices
    response_variable: dev_data
    data:
      command_data: last_seen,device_type,entities
  - repeat:
      for_each: "{{ dev_data.devices }}"
      sequence:
        - condition: template
          value_template: "{{ repeat.item.device_type == 'EndDevice' }}"
        - variables:
            last_seen: "{{ repeat.item.last_seen }}"
        - repeat:
            for_each: "{{ repeat.item.entities }}"
            sequence:
              - service: zha_toolkit.ha_set_state
                data:
                  attr_val: "{{ last_seen }}"
                  state_id: "{{ repeat.item.entity_id }}"
                  state_attr: last_seen
mode: single
```
