### ISSUE TITLE
dst_endpoint not reflected in binding

### ISSUE THREAD

**Issue by kdsp-net** [mdeweerd/zha-toolkit#272]
Hi, I'm trying to bind several wireless sensors (Sonoff SNZB-02P) to my UFH Controller (Ubisys H10). I can bind the sensor to the temperature measurement cluster on endpoint 1 withou any problems but when i try to set the dst_endpoint parameter to the second sensor it gets ignored and the sensor gets bound to the endpoint 1 regardles. Here is the command log:

```
zha_toolkit_version: v1.1.19
zigpy_version: 0.73.1
zigpy_rf_version: 0.13.1
ieee_org: <sanitized>
ieee: <sanitized>
command: bind_ieee
command_data: <sanitized>
start_time: "2024-12-14T16:08:04.795447+00:00"
errors: []
params:
  endpoint_id: 1
  dst_endpoint_id: 2 <-- here the destination is "2"
  dir: 0
  tries: 1
  expect_reply: true
  args: []
  read_before_write: true
  read_after_write: true
result:
  "1":
    src_endpoint_id: 1
    dst_endpoint_id: 1 <-- here the destination is "1"
    cluster_id: 1026
    result:
      - 0
success: true
```

I have also contacted Ubisys since I'm not sure who's "at fault" here.
