### ISSUE TITLE
Misc Energy Scan Missing?

### ISSUE THREAD

**Issue by 400HPMustang** [mdeweerd/zha-toolkit#285]
Integration version 1.1.25
HAOS: 2025.1.4

Installed the tool wanting to run an energy scan but that seems to be missing. 

<img width="1321" alt="Image" src="https://github.com/user-attachments/assets/fa177b2a-87ba-466a-a230-ce40403114db" />

<img width="1261" alt="Image" src="https://github.com/user-attachments/assets/72a35eb5-5a2b-4d90-bea3-1a808c96fce2" />

**Comment by 400HPMustang** [comment]
> It's a recent contribution [#283](https://github.com/mdeweerd/zha-toolkit/pull/283) and I am waiting for [#284](https://github.com/mdeweerd/zha-toolkit/pull/284) to be finalized before making a release.

ETA?

**Comment by mdeweerd** [comment]
I finalized the PR and published.

**Comment by 400HPMustang** [comment]
I just updated to 1.1.26 and still not available.

**Comment by mdeweerd** [comment]
The service was not added to services.yaml.

You can still run it like this:

```
action: zha_toolkit.execute
data:
  command: misc_energy_scan
```

**Comment by rrooggiieerr** [comment]
Maybe update the documentation accordingly? Because 

```yaml
action: zha_toolkit.misc_energy_scan
data:
  # Optional: CSV file to write attribute to - located in /config/csv/...
  csvout: energy_scan.csv
```

as stated in the documentation is not working

**Comment by rrooggiieerr** [comment]
The thing is that `zha_toolkit.misc_energy_scan` does not exist. It's not in the `services.yaml` and you need to use the

```yaml
action: zha_toolkit.execute
data:
  command: misc_energy_scan
```

instead of 

```yaml
action: zha_toolkit.misc_energy_scan
data:
  # Optional: CSV file to write attribute to - located in /config/csv/...
  csvout: energy_scan.csv
```
